// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryAppWpf.DbModel
{
    public partial class BookAuthor
    {
        public BookAuthor()
        {
            Book = new HashSet<Book>();
        }

        public int Id { get; set; }
        public string Fullname { get; set; }
        public DateTime BirthDate { get; set; }
        public DateTime? DeathDate { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Book> Book { get; set; }
    }
}