// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryAppWpf.DbModel
{
    public partial class Book
    {
        public Book()
        {
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int AuthorId { get; set; }
        public string Keywords { get; set; }
        public DateTime Date { get; set; }
        public int Quantity { get; set; }

        public virtual BookAuthor Author { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}