// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryAppWpf.DbModel
{
    public partial class Student
    {
        public Student()
        {
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public DateTime BirthDate { get; set; }
        public DateTime EntryYear { get; set; }
        public bool? StillThere { get; set; }
        public int AmountOfDebts { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}